spring:
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
    database: 0
    sentinel:
      master: mymaster
      nodes: 172.100.0.15:26379,172.100.0.16:26379,172.100.0.17:26379
    password: 123456
