version: "3"
services:
  master:
    image: redis:4.0
    container_name: redis-master-6300
    ports: 
      - 6300:6379
    command: redis-server /etc/redis/redis.conf #--appendonly yes
    volumes:
      - /Users/ext.wangxintian1/db/redis/1master3slave3sentinal/redis-m.conf:/etc/redis/redis.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.11
  slave1:
    image: redis:4.0
    container_name: redis-slave-6301
    depends_on:
      - master
    ports:
      - 6301:6379
    command: redis-server /etc/redis/redis.conf #--appendonly yes
    volumes:
      - /Users/ext.wangxintian1/db/redis/1master3slave3sentinal/redis-s.conf:/etc/redis/redis.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.12
  slave2:
    image: redis:4.0
    container_name: redis-slave-6302
    depends_on:
      - master
    ports:
      - 6302:6379
    command: redis-server /etc/redis/redis.conf #--appendonly yes
    volumes:
      - /Users/ext.wangxintian1/db/redis/1master3slave3sentinal/redis-s.conf:/etc/redis/redis.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.13
  slave3:
    image: redis:4.0
    container_name: redis-slave-6303
    depends_on:
      - master
    ports:
      - 6303:6379
    command: redis-server /etc/redis/redis.conf #--appendonly yes
    volumes:
      - /Users/ext.wangxintian1/db/redis/1master3slave3sentinal/redis-s.conf:/etc/redis/redis.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.14
  sentinel1:
    image: redis:4.0
    container_name: sentinel1
    depends_on:
      - slave3
    ports:
      - 26379:26379
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - /Users/ext.wangxintian1/db/redis/1master3slave3sentinal/sentinel.conf:/etc/redis/sentinel.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.15
  sentinel2:
    image: redis:4.0
    container_name: sentinel2
    depends_on:
      - slave3
    ports:
      - 26380:26379
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - /Users/ext.wangxintian1/db/redis/1master3slave3sentinal/sentinel.conf:/etc/redis/sentinel.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.16
  sentinel3:
    image: redis:4.0
    container_name: sentinel3
    depends_on:
      - slave3
    ports:
      - 26381:26379
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - /Users/ext.wangxintian1/db/redis/1master3slave3sentinal/sentinel.conf:/etc/redis/sentinel.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.17
networks:
  extnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
          gateway: 172.100.0.1
        